# Generated by Django 5.1.7 on 2025-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('MedalType', models.TextField(choices=[('Gold', 'Gl'), ('Silver', 'Sl'), ('Bronze', 'Br')], default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place_ptr',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
