# Generated by Django 5.1.7 on 2025-05-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_position_remove_restaurant_place_ptr_delete_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='MedalType',
            field=models.TextField(choices=[('Gold', 'Gl'), ('Silver', 'Sl'), ('Bronze', 'Br')]),
        ),
    ]
