# Generated by Django 5.1.7 on 2025-05-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_position_medaltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='MedalType',
            new_name='Medaltype',
        ),
    ]
