# Generated by Django 5.1.7 on 2025-05-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_rename_medaltype_position_medaltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='Medaltype',
            field=models.TextField(choices=[('GL', 'Gold'), ('SL', 'Silver'), ('BR', 'Bronze')]),
        ),
    ]
