# Generated by Django 5.2.1 on 2025-05-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recepie',
        ),
    ]
