# Generated by Django 5.2.1 on 2025-05-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_rename_receipe_description_recepie_recepie_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recepie',
        ),
    ]
