# Generated by Django 5.1.7 on 2025-05-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choieces',
            new_name='choices',
        ),
    ]
