# Generated by Django 5.1.7 on 2025-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_choieces_choice_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choices',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Gradute')], default='Freshman', max_length=10),
        ),
    ]
