# Generated by Django 5.2.1 on 2025-05-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_choice_choices_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
    ]
